title: Gabay
description: Gabay homepage.
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme

# Build settings
# markdown: kramdown
# theme: minima
# plugins:
#   - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - .bundle/
  - .github
  - .gitignore
