format = """
$cmd_duration\
[░▒▓](#a3aed2)\
[ $username@$hostname ](fg:#090c0c bg:#a3aed2)\
$directory\
$git_branch\
$git_status\
$time\
$character"""

[cmd_duration]
format = '[\[$duration\] ]($style)'
style = "bold fg:#a0a9cb"

[username]
show_always = true
format = '[$user]($style)'
style_user = "fg:#090c0c bg:#a3aed2"
style_root = "bold fg:#8c4351 bg:#a3aed2"

[hostname]
ssh_only = false
format = '[$hostname]($style)'
style = "fg:#090c0c bg:#a3aed2"

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
style = "bg:#394260"
format = '[[ $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[ $time ](fg:#a0a9cb bg:#1d2230)]($style)'

